dist: bionic
language: ruby
rvm: 2.7
before_script:
  - wget https://github.com/ankane/ml-builds/releases/download/libmf-v201/libmf.so
  - mv libmf.so lib/libmf.so
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
