image: Visual Studio 2017
platform: x64
configuration: Release

environment:
  matrix:
    - RUBY_VERSION: "26-x64"

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

build_script:
  - git submodule update --init --recursive
  - bundle exec ruby ext/libmf/extconf.rb
  - rm vendor/libmf/windows/mf.dll
  # - curl -o vendor/libmf/windows/mf.dll https://github.com/ankane/ml-builds/releases/download/libmf-v201/mf.dll
  - ls vendor/libmf/windows

test_script:
  - bundle exec rake test
