environment:
  matrix:
    - RUBY_VERSION: "25-x64"

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

build_script:
  - git submodule update --init --recursive
  - bundle exec ruby ext/libmf/extconf.rb
  - set "DUMPBIN=%VS140COMNTOOLS%\..\..\VC\bin\dumpbin.exe"
  - '"%DUMPBIN%" /exports vendor/libmf/windows/mf.dll

test_script:
  - bundle exec rake test
